### ISSUE TITLE
what is the use of this accordian? Day-1 Rohit Singh

### ISSUE THREAD

**Issue by 9868rishi** [Guruprasad3n/HubSpot.com---Clone#49]
https://github.com/Guruprasad3n/HubSpot.com---Clone/blob/a5f345baaea8a0e407a899a213e3d1b0537a2856/Frontend/hubspot/src/Components/Footer/FooterAccordion.jsx#L12

**Comment by RohitSinghChauhan** [comment]
Issue has been fixed.
