### ISSUE TITLE
why you are using the same accordian for all the different thing? -Day-1 Rohit Singh

### ISSUE THREAD

**Issue by 9868rishi** [Guruprasad3n/HubSpot.com---Clone#50]
https://github.com/Guruprasad3n/HubSpot.com---Clone/blob/a5f345baaea8a0e407a899a213e3d1b0537a2856/Frontend/hubspot/src/Components/Footer/FooterAccordion.jsx#L22

**Comment by RohitSinghChauhan** [comment]
Issue has been fixed now.
