### ISSUE TITLE
why you are opening this in different tab - Day-3 Rohit Singh

### ISSUE THREAD

**Issue by 9868rishi** [Guruprasad3n/HubSpot.com---Clone#53]
https://github.com/Guruprasad3n/HubSpot.com---Clone/blob/a5f345baaea8a0e407a899a213e3d1b0537a2856/Frontend/hubspot/src/Components/Navbar/MenuComp.jsx#L37

**Comment by RohitSinghChauhan** [comment]
Issue for opening links  of other page on different tab has been fixed
