### ISSUE TITLE
Why you are redirecting to any other page - Day-2 Rohit Singh

### ISSUE THREAD

**Issue by 9868rishi** [Guruprasad3n/HubSpot.com---Clone#54]
https://github.com/Guruprasad3n/HubSpot.com---Clone/blob/a5f345baaea8a0e407a899a213e3d1b0537a2856/Frontend/hubspot/src/Components/Navbar/Navbar.jsx#L35

**Comment by RohitSinghChauhan** [comment]
issue for redirecting user to other site's page has been fixed.
