### ISSUE TITLE
css should be in different file - Day-1 Rohit Singh 

### ISSUE THREAD

**Issue by 9868rishi** [Guruprasad3n/HubSpot.com---Clone#55]
https://github.com/Guruprasad3n/HubSpot.com---Clone/blob/a5f345baaea8a0e407a899a213e3d1b0537a2856/Frontend/hubspot/src/Components/Navbar/Navbar.jsx#L34

**Comment by RohitSinghChauhan** [comment]
Completed, as chakra-UI provides components that required attributes as props in the brackets of a component thus, no specific need of making a separate css file.
